version: "3.7"
services:
  db:
      image: mysql:8.0.19
      command: '--default-authentication-plugin=mysql_native_password'
      restart: always
      environment: 
          - MYSQL_DATABASE=example
          - MYSQL_ROOT_PASSWORD=mysql_native_password

  app:
      build: app
      restart: always

  web:
        build: web
        restart: always
        ports: 
          - 80:80
          